/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e4e2e1',
        'tertiary-fixed-dim': '#78dc77',
        'tertiary': '#006e1c',
        'on-error': '#ffffff',
        'surface-bright': '#fff8f6',
        'surface-variant': '#f4ded8',
        'inverse-on-surface': '#ffede8',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#474747',
        'surface-container-highest': '#f4ded8',
        'primary-fixed-dim': '#ffb59f',
        'on-background': '#241916',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#002204',
        'on-secondary-fixed': '#1b1c1c',
        'on-primary-fixed-variant': '#852401',
        'on-tertiary-container': '#003b0b',
        'inverse-surface': '#3b2d2a',
        'inverse-primary': '#ffb59f',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-dim': '#ebd5d0',
        'surface': '#fff8f6',
        'tertiary-fixed': '#94f990',
        'primary-container': '#f4744c',
        'background': '#fff8f6',
        'primary-fixed': '#ffdbd0',
        'secondary-fixed-dim': '#c8c6c6',
        'surface-container': '#ffe9e3',
        'surface-tint': '#a63b17',
        'on-surface': '#241916',
        'outline-variant': '#dfc0b7',
        'on-surface-variant': '#57423b',
        'tertiary-container': '#4bae4f',
        'surface-container-high': '#fae3dd',
        'surface-container-low': '#fff1ed',
        'error': '#ba1a1a',
        'on-primary-fixed': '#3a0a00',
        'secondary': '#5f5e5e',
        'on-secondary-container': '#656464',
        'secondary-container': '#e4e2e1',
        'outline': '#8b716a',
        'on-primary-container': '#611700',
        'primary': '#a63b17',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#005313',
      },
      fontFamily: {
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
